"""
===============================================================================
EduFlow AI - Shared Agent State & Workflow Status Models
===============================================================================
This module defines the foundational State Architecture for the EduFlow AI
multi-agent platform based on LangGraph principles.

Why we use this module:
1. Blackboard Architecture Pattern:
   - Multiple specialized agents (Planner, Domain Analysis, Content/Tool, Validation Guard)
     collaborate by reading and writing to a single shared blackboard state (`SharedAgentState`).
2. Bounded Memory Footprint:
   - Large tool outputs, logs, and telemetry are stored in structured dictionary references
     to prevent runaway memory consumption.
3. State Machine Governance:
   - `WorkflowStatus` provides a deterministic enum to guarantee that AI workflows
     transition only through strictly permitted human-in-the-loop and validation states.
"""

# Import standard library enum support for creating strongly-typed enumerated status values
from enum import Enum
# Import typing annotations for flexible type hints across dictionaries, lists, and optional fields
from typing import Dict, Any, List, Optional
# Import Pydantic BaseModel and Field to enable runtime data validation, serialization, and schema generation
from pydantic import BaseModel, Field


# -----------------------------------------------------------------------------
# 1. Workflow Status Enumeration
# -----------------------------------------------------------------------------
class WorkflowStatus(str, Enum):
    """
    Defines the valid lifecycle states for any multi-agent workflow graph.
    
    Why we use an Enum:
    - Eliminates typo-prone string literals across the codebase.
    - Enables the ApprovalStateMachine to validate legal state transitions deterministically.
    
    State Progression:
    - DRAFT: Initial workflow creation before agent planning.
    - VALIDATING: The output is being checked by deterministic validation guardrails.
    - PENDING_APPROVAL: Output passed validation and awaits human instructor sign-off.
    - APPROVED: Instructor has reviewed and explicitly approved the proposal.
    - REVISION_REQUESTED: Instructor requested modifications; loops back to Planner.
    - REJECTED: Instructor rejected the proposal permanently; workflow terminates.
    - EXECUTING: Approved workflow actions are actively executing.
    - COMPLETED: All workflow steps have successfully completed.
    - FAILED: A critical error, unrecoverable exception, or validation failure occurred.
    """
    DRAFT = "DRAFT"                               # Initial state when workflow is created
    VALIDATING = "VALIDATING"                     # Actively undergoing deterministic validation rules
    PENDING_APPROVAL = "PENDING_APPROVAL"         # Gated waiting for human instructor approval
    APPROVED = "APPROVED"                         # Successfully approved by human instructor
    REVISION_REQUESTED = "REVISION_REQUESTED"     # Feedback provided; requires planner re-execution
    REJECTED = "REJECTED"                         # Denied by instructor; no execution occurs
    EXECUTING = "EXECUTING"                       # Approved actions are currently running
    COMPLETED = "COMPLETED"                       # Workflow reached end state successfully
    FAILED = "FAILED"                             # Unrecoverable error or hard validation failure


# -----------------------------------------------------------------------------
# 2. Plan Step Model
# -----------------------------------------------------------------------------
class PlanStep(BaseModel):
    """
    Represents an atomic, actionable step generated by the Coordinator/Planner Agent.
    
    Why we use this model:
    - Breaks complex educational goals down into discrete, assignable sub-tasks.
    - Explicitly assigns ownership to specific agent roles to avoid ambiguity.
    """
    # Unique identifier for the step (e.g., '1', 'step-fetch-progress')
    stepId: str
    
    # Name of the permitted action to be taken (e.g., 'GET_STUDENT_PROGRESS', 'ANALYZE_PROGRESS')
    action: str
    
    # The authorized agent role assigned to execute this step
    # Permitted roles: "COORDINATOR_PLANNER" | "ACTION_TOOL" | "DOMAIN_ANALYSIS" | "VALIDATION_SAFETY"
    owner: str
    
    # Key-value parameters passed into the executing agent or tool
    params: Dict[str, Any] = Field(default_factory=dict)
    
    # Current execution status of this individual step (PENDING | IN_PROGRESS | COMPLETED | FAILED)
    status: str = "PENDING"


# -----------------------------------------------------------------------------
# 3. Tool Result Item Model
# -----------------------------------------------------------------------------
class ToolResultItem(BaseModel):
    """
    Represents the output record produced whenever an agent executes a permitted tool.
    
    Why we use this model:
    - Provides full auditability of tool calls, latencies, and output payloads.
    - Supports reference-based storage for large datasets (resultRef).
    """
    # The name of the registered tool executed (e.g., 'get_course_content', 'create_quiz_draft')
    toolName: str
    
    # The agent role or entity that initiated the tool call
    executedBy: str
    
    # Total execution duration in milliseconds for observability tracking
    durationMs: int
    
    # Optional pointer / URI / hash to external blob storage if the tool output is massive
    resultRef: Optional[str] = None
    
    # The structured JSON payload returned by the tool handler
    data: Dict[str, Any] = Field(default_factory=dict)


# -----------------------------------------------------------------------------
# 4. Approval Record Model
# -----------------------------------------------------------------------------
class ApprovalRecord(BaseModel):
    """
    Maintains the Human-in-the-Loop (HITL) review history and governance state.
    
    Why we use this model:
    - Enforces safety: Ensures AI-generated curriculum alterations require human instructor consent.
    - Maintains an audit trail of who reviewed what, when, and what comments they provided.
    """
    # Flag indicating whether human approval is mandatory for this workflow (default True)
    required: bool = True
    
    # Current review state: "PENDING" | "APPROVED" | "REJECTED" | "REVISION_REQUESTED" | "AUTO_APPROVED"
    status: str = "PENDING"
    
    # Identifier of the instructor or reviewer who made the decision
    reviewerId: Optional[str] = None
    
    # ISO-8601 timestamp recording when the decision was submitted
    reviewedAt: Optional[str] = None
    
    # Optional feedback, explanation, or revision instructions from the reviewer
    comments: Optional[str] = None
    
    # Counter tracking how many revision cycles this proposal has undergone
    revisionCount: int = 0


# -----------------------------------------------------------------------------
# 5. Standardized EduFlow AI Shared Agent State (Blackboard)
# -----------------------------------------------------------------------------
class SharedAgentState(BaseModel):
    """
    Standardized EduFlow AI Shared Agent State (Blackboard).
    Contains the 11 core state fields with reference storage for bounded memory footprint.
    
    Why we use this model:
    - Serves as the single source of truth across all LangGraph nodes and interconnected agents.
    - Each agent reads only the fields it needs and updates its designated output fields.
    - Persists observability metrics, execution logs, validation checks, and approval gates.
    """
    # 1. Unique workflow identifier (e.g., "wf-a1b2c3d4")
    workflowId: str
    
    # 2. Unique UUID of the student associated with this learning workflow
    studentId: str
    
    # 3. High-level goal specification (target goal, target weeks, hours per week, etc.)
    objective: Dict[str, Any] = Field(default_factory=dict)
    
    # 4. Student historical context (course ID, past scores, streaks, time on task, mistakes)
    studentContext: Dict[str, Any] = Field(default_factory=dict)
    
    # 5. List of decomposed steps produced by the Coordinator/Planner Agent
    plan: List[Dict[str, Any]] = Field(default_factory=list)
    
    # 6. Audit list of all tool executions, latencies, and tool results
    toolResults: List[Dict[str, Any]] = Field(default_factory=list)
    
    # 7. Grounded telemetry diagnostics produced by the Domain Analysis Agent (gaps, strengths)
    analysis: Dict[str, Any] = Field(default_factory=dict)
    
    # 8. AI-synthesized content drafts (study schedule, quiz questions, challenges)
    candidateOutput: Dict[str, Any] = Field(default_factory=dict)
    
    # 9. Results of the 5-layer deterministic validation checks produced by ValidationGuardAgent
    validation: Dict[str, Any] = Field(default_factory=dict)
    
    # 10. Human instructor approval state, reviewer comments, and revision timestamps
    approval: Dict[str, Any] = Field(default_factory=dict)
    
    # 11. Current workflow lifecycle status (from WorkflowStatus enum)
    status: str = WorkflowStatus.DRAFT.value

    # Additional observability / metadata fields:
    # Detailed execution logs from every agent involved in the pipeline
    executionLogs: List[Dict[str, Any]] = Field(default_factory=list)
    
    # Aggregated performance metrics (durations, tool latencies, token usage counts)
    observabilityMetrics: Dict[str, Any] = Field(default_factory=dict)

    def to_graph_dict(self) -> Dict[str, Any]:
        """
        Converts the Pydantic state model into a standard Python dictionary
        compatible with LangGraph state channels.
        """
        # model_dump() serializes all fields into a pure python dictionary
        return self.model_dump()

    @classmethod
    def from_graph_dict(cls, data: Dict[str, Any]) -> "SharedAgentState":
        """
        Reconstructs a strongly-typed SharedAgentState instance from a LangGraph dictionary.
        """
        # Unpack dictionary keys into the constructor for validation
        return cls(**data)
