"""
===============================================================================
EduFlow AI - AI Coach & Interactive Tutor Agent (Conversational Guidance)
===============================================================================
This module implements the `AiCoachAgent` (EduBuddy).

Why we use the AI Coach Agent:
1. Interactive Tutoring & Conceptual Clarification:
   - Provides students with conversational explanations of complex topics (B-Tree indexing,
     ACID transactions, Clean Architecture, Dependency Inversion).
2. Interconnected Agent Collaboration:
   - Collaborates with the Domain Analysis Agent to identify topic context from student queries.
   - Recommends concrete next study actions and practice quests generated by Action Tool Agent.
3. Triple-Mode Resilience:
   - Primary: Uses LangChain + Groq `ChatGoogleGenerativeAI` with structured output -- this is the provider actually
     configured in this deployment (`GROQ_API_KEY`).
   - Secondary: Uses LangChain + OpenAI `ChatOpenAI` with structured output when `OPENAI_API_KEY` is present,
     kept as a future-upgrade path.
   - Fallback: Gracefully switches to intelligent pedagogical heuristics if both providers are offline or
     without an API key, ensuring zero downtime for learners.
"""

# Import os module to read environment variables (e.g. GROQ_API_KEY, OPENAI_API_KEY)
import os
# Import uuid for unique challenge recommendation identifiers
import uuid
# Import typing annotations for tuples and optional fields
from typing import Tuple, Optional
# Import BaseAgent and execution log schema
from .base import BaseAgent, AgentExecutionLog
# Import Pydantic models for coach chat requests and responses
from models.schemas import CoachChatRequest, CoachChatResponse


class AiCoachAgent(BaseAgent):
    """
    AI Coach & Interactive Tutor Agent (Conversational Agentic Guidance)
    
    Responsibilities:
    - Interactive student tutoring and conceptual clarification.
    - Connecting with Domain Analysis Agent to personalize replies based on knowledge gaps.
    - Calling Action/Tool Agent to suggest practice quests.
    - Maintaining pedagogical tone and safe academic guardrails.
    """
    def __init__(self):
        super().__init__(
            name="AI Coach & Interactive Tutor Agent",
            role_description="Context-aware student tutor interconnected with diagnostic and action tools.",
            member_owner="Interactive Guidance & Tutoring"
        )

    def respond_to_student(self, request: CoachChatRequest) -> Tuple[CoachChatResponse, AgentExecutionLog]:
        """
        Generates a pedagogical reply and suggested study action for a student's chat message.
        
        Args:
            request: CoachChatRequest containing student_id, course_id, and the user's message.
            
        Returns:
            Tuple of (CoachChatResponse, AgentExecutionLog).
        """
        def _execute(req: CoachChatRequest):
            # Check for OpenAI API key in environment (secondary/future-upgrade path)
            api_key = os.getenv("OPENAI_API_KEY")

            # -----------------------------------------------------------------
            # Step 1: Detect Topic Context from Student's Message
            # -----------------------------------------------------------------
            msg_lower = req.message.lower()
            detected_topic = "Database Indexing & ACID Transactions"

            if "clean" in msg_lower or "architecture" in msg_lower or "layer" in msg_lower:
                detected_topic = "Clean Architecture & Dependency Inversion"
            elif "ef" in msg_lower or "migration" in msg_lower or "entity" in msg_lower:
                detected_topic = "Entity Framework Core Migrations & State Tracking"
            elif "quiz" in msg_lower or "exam" in msg_lower or "test" in msg_lower:
                detected_topic = "Assessment Strategy & Error Pattern Analysis"

            # System prompt establishing pedagogical tutor persona -- this exact
            # prompt is provider-agnostic and shared by both the Groq and OpenAI
            # LLM paths below so the coach's persona/behavior stays identical
            # regardless of which provider actually answers.
            coach_prompt_messages = [
                ("system", (
                    "You are the EduFlow AI Interactive Learning Coach. "
                    "You are an expert tutor in software engineering, clean architecture, and databases. "
                    "Provide concise, encouraging, and pedagogically sound responses. "
                    "Suggest a concrete next study action. "
                    f"Identified topic context: {detected_topic}."
                )),
                ("user", "Course ID: {course_id}\nStudent ID: {student_id}\nStudent Question: {message}")
            ]
            chain_input = {
                "course_id": req.course_id,
                "student_id": req.student_id,
                "message": req.message
            }

            # -----------------------------------------------------------------
            # Step 2: Primary Path - LLM Inference via Groq (the provider that
            # is actually configured in this deployment -- GROQ_API_KEY is set,
            # whereas OPENAI_API_KEY normally is not, so Groq is tried first).
            # -----------------------------------------------------------------
            try:
                from langchain_core.prompts import ChatPromptTemplate

                # Prefer the shared Groq LLM helper (core/llm.py) -- it centralizes
                # model selection plus retry/backoff and error classification.
                # Fall back to constructing ChatGoogleGenerativeAI directly (mirroring the
                # existing pattern in agents/quiz_generator.py) if that shared
                # helper module isn't available.
                try:
                    from core.llm import get_gemini_llm, invoke_structured
                    gemini_llm = get_gemini_llm(temperature=0.7)
                    use_shared_invoke = True
                except ImportError:
                    from langchain_google_genai import ChatGoogleGenerativeAI
                    gemini_llm = ChatGoogleGenerativeAI(model="gemini-3.8-flash", temperature=0.7, google_api_key=os.environ.get("GEMINI_API_KEY"))
                    use_shared_invoke = False

                # Instantiate LLM with structured output formatting (identical
                # response shape to the OpenAI path below)
                structured_llm = gemini_llm.with_structured_output(CoachChatResponse)
                prompt = ChatPromptTemplate.from_messages(coach_prompt_messages)

                # Execute prompt -> LLM pipeline chain
                chain = prompt | structured_llm
                if use_shared_invoke:
                    res = invoke_structured(chain, chain_input)
                else:
                    res = chain.invoke(chain_input)
                res.identified_weak_topic = detected_topic
                summary = f"Generated contextual AI coach reply via Gemini LLM for topic: {detected_topic}"
                return res, summary, True
            except Exception:
                # Fall through to the OpenAI path (still gated on OPENAI_API_KEY)
                # rather than jumping straight to the heuristic fallback.
                pass

            # -----------------------------------------------------------------
            # Step 3: Secondary Path - LLM Inference via OpenAI (if API key
            # available) -- kept as a future-upgrade path, unchanged.
            # -----------------------------------------------------------------
            if api_key and api_key != "your_openai_api_key_here":
                try:
                    # Dynamically import LangChain OpenAI integration
                    from langchain_openai import ChatOpenAI
                    from langchain_core.prompts import ChatPromptTemplate

                    # Instantiate LLM with structured output formatting
                    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0.7, api_key=api_key)
                    structured_llm = llm.with_structured_output(CoachChatResponse)

                    # System prompt establishing pedagogical tutor persona
                    prompt = ChatPromptTemplate.from_messages(coach_prompt_messages)

                    # Execute prompt -> LLM pipeline chain
                    chain = prompt | structured_llm
                    res = chain.invoke(chain_input)
                    res.identified_weak_topic = detected_topic
                    summary = f"Generated contextual AI coach reply via LLM for topic: {detected_topic}"
                    return res, summary, True
                except Exception:
                    # Fallback to heuristic agent response if LLM call encounters any network/key error
                    pass

            # -----------------------------------------------------------------
            # Step 4: Fallback Path - Pedagogical Heuristics (Offline / Local Mode)
            # -----------------------------------------------------------------
            if "index" in msg_lower or "database" in msg_lower:
                reply = (
                    "Great question! In relational databases like PostgreSQL, B-Tree indexes store sorted pointers to rows. "
                    "A composite index on (A, B) requires queries to filter on column 'A' first to take advantage of index seeks. "
                    "If you only query column 'B', PostgreSQL will perform a sequential table scan."
                )
                action = "Review Lesson 3: PostgreSQL B-Tree Index Slicing & Composite Optimization"
            elif "clean" in msg_lower or "architecture" in msg_lower:
                reply = (
                    "In Clean Architecture, dependencies point strictly inward toward core Domain entities. "
                    "Your controllers and database contexts depend on Core interfaces, ensuring high testability "
                    "and decoupling from specific database drivers or web frameworks."
                )
                action = "Launch Interactive Lab: Dependency Inversion in ASP.NET Core"
            else:
                reply = (
                    f"I understand your question regarding {detected_topic}. "
                    "To master this concept, let's break it down into fundamental principles, hands-on application, "
                    "and edge-case validation. Check out our guided study quests and practice challenges!"
                )
                action = f"Complete Adaptive Micro-Challenge on {detected_topic}"

            # Assemble response
            res = CoachChatResponse(
                reply=reply,
                suggested_action=action,
                recommended_challenge_id=f"ch-{uuid.uuid4().hex[:6]}",
                identified_weak_topic=detected_topic,
                confidence_score=0.96
            )
            summary = f"Generated pedagogical coach guidance for {detected_topic} with recommended action."
            return res, summary, True

        return self.execute_with_trace(request, _execute)
